### <u><B> *APRIORI ALGORITHM*</B></U>

Apriori is an unsupervised learning algorithm used for 

-> ASSOCIATION RULE MINING

Apriori finds patterns like :

"People who buys X often also buy Y

It works on TRANSACTIONAL DATA

In [7]:
import pandas as pd


transactions = [
    ['Beer','Diaper'],
    ['Milk', 'Diaper', 'Bread','Butter'],
    ['Bread', 'Butter'],
    ['Milk', 'Bread', 'Butter'],
    ['Beer','Cookies', 'Diaper']
]

transactions

[['Beer', 'Diaper'],
 ['Milk', 'Diaper', 'Bread', 'Butter'],
 ['Bread', 'Butter'],
 ['Milk', 'Bread', 'Butter'],
 ['Beer', 'Cookies', 'Diaper']]

Convert transactions → one-hot encoded DataFrame

In [8]:
from mlxtend.preprocessing import TransactionEncoder

te=TransactionEncoder()
te_array = te.fit(transactions).transform(transactions)

df=pd.DataFrame(te_array,columns=te.columns_)
df

    Beer  Bread  Butter  Cookies  Diaper   Milk
0   True  False   False    False    True  False
1  False   True    True    False    True   True
2  False   True    True    False   False  False
3  False   True    True    False   False   True
4   True  False   False     True    True  False

Apply apriori algorithm

In [9]:
from mlxtend.frequent_patterns import apriori

freq_itemsets=apriori(
    df,
    min_support=0.4,
    use_colnames=True
)

freq_itemsets

   support               itemsets
0      0.4                 (Beer)
1      0.6                (Bread)
2      0.6               (Butter)
3      0.6               (Diaper)
4      0.4                 (Milk)
5      0.4         (Beer, Diaper)
6      0.6        (Butter, Bread)
7      0.4          (Bread, Milk)
8      0.4         (Butter, Milk)
9      0.4  (Butter, Bread, Milk)

Generate association rule:

In [10]:
from mlxtend.frequent_patterns import association_rules

rules=association_rules(
    freq_itemsets,
    metric='confidence',
    min_threshold=0.6
)

rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']]

        antecedents      consequents  support  confidence      lift
0            (Beer)         (Diaper)      0.4    1.000000  1.666667
1          (Diaper)           (Beer)      0.4    0.666667  1.666667
2          (Butter)          (Bread)      0.6    1.000000  1.666667
3           (Bread)         (Butter)      0.6    1.000000  1.666667
4           (Bread)           (Milk)      0.4    0.666667  1.666667
5            (Milk)          (Bread)      0.4    1.000000  1.666667
6          (Butter)           (Milk)      0.4    0.666667  1.666667
7            (Milk)         (Butter)      0.4    1.000000  1.666667
8   (Butter, Bread)           (Milk)      0.4    0.666667  1.666667
9    (Butter, Milk)          (Bread)      0.4    1.000000  1.666667
10    (Bread, Milk)         (Butter)      0.4    1.000000  1.666667
11         (Butter)    (Bread, Milk)      0.4    0.666667  1.666667
12          (Bread)   (Butter, Milk)      0.4    0.666667  1.666667
13           (Milk)  (Butter, Bread)      0.4    1.000000  1.666667