### <u><B> *TEXT PREPROCESSING*</B></U>

1. Basic text preprocessing and 
2. Advanced text preprocessing
- Parts of Speech(POS) tag
- Chunking
- Parsing
- Core reference resolution

In [163]:
import pandas as pd

In [164]:
df= pd.read_csv("IMDB Dataset.csv")
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [165]:
df.shape

(50000, 2)

#### 1.LOWERCASING

In [166]:
df['review']=df['review'].str.lower()

In [167]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. <br /><br />the...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

#### 2. REMOVE HTML TAGS

In [168]:
import re
def remove_html_tags(text):
    pattern=re.compile("<.*?>")
    return pattern.sub(r'',text)

In Python, the re library stands for Regular Expressions.

It is used for pattern matching and text processing.

without .*? is greedy , It matches as much as possible

r'' → replace with empty string

In [169]:
text="<html><body><h1>Breaking News!</h1><p>This <b>movie</b> was <i>absolutely amazing</i> 😍.</p><br><p>Visit <a href='https://example.com'>our site</a> for more <span style='color:red;'>updates</span>.</p><!-- end of article --></body></html>"
remove_html_tags(text)

'Breaking News!This movie was absolutely amazing 😍.Visit our site for more updates.'

In [170]:
df['review'][3]

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.<br /><br />ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

In [171]:
df['review']=df['review'].apply(remove_html_tags)

In [172]:
df['review'][3]

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

#### 3.REMOVE URLs

In [173]:
def remove_url(text):
    pattern= re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r'',text)

http -> matches literal 

s? -> means optional , matches both http and https

:// -> matches literal

\S+ -> one or more non white space characters

| -> or , the second part

In [174]:
text="Check this article https://example.com and visit www.test.com for more info."
remove_url(text)

'Check this article  and visit  for more info.'

#### 4. REMOVE PUNCTUATION

In [175]:
import string,time
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [176]:
exclude=string.punctuation

In [177]:
def remove_punc(text):
    for char in exclude:
        text=text.replace(char,'')
    return text

In [178]:
text= "{String with punctuation??/;}"
start = time.time()
print(remove_punc(text))
time1=time.time() - start #to measure how much tym will take to complete the entire process
print(time1)

String with punctuation
0.00042176246643066406

this will take a lot of time

so an another technique can be used

In [179]:
def remove_punc1(text):
    return text.translate(str.maketrans('','',exclude))

str.maketrans(x, y, z)

Where:

- x → characters to replace

- y → characters to replace with

- z → characters to delete

str.maketrans('','',exclude)

Meaning:

- Replace nothing

- With nothing

- Delete everything inside exclude

translate() applies that translation table to the string.

In [180]:
start= time.time()
remove_punc1(text)
time2=time.time()-start
print(time2)

0.00011897087097167969

In [181]:
time1/time2

# We can find that the second function is 6 times faster than the first one

3.5450901803607215

In [182]:
df['review']=df['review'].apply(remove_punc1)
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production the filming tech...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically theres a family where a little boy j...  negative
4      petter matteis love in the time of money is a ...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot bad dialogue bad acting idiotic direc...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  im going to have to disagree with the previous...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

#### 5.CHAT WORD TREATMENT

We use a lot of short terms while we chat , like , ASAP, BRB, GN, FR, etc , and we need to treat that

In [183]:
chat_words = {
    "afaik": "as far as I know",
    "afk": "away from keyboard",
    "asl": "age, sex, location",
    "atm": "at the moment",
    "b4": "before",
    "bae": "before anyone else",
    "bb": "bye bye",
    "bbl": "be back later",
    "bc": "because",
    "bf": "boyfriend",
    "bff": "best friends forever",
    "brb": "be right back",
    "btw": "by the way",
    "cya": "see you",
    "dm": "direct message",
    "fomo": "fear of missing out",
    "ftw": "for the win",
    "fyi": "for your information",
    "gg": "good game",
    "gf": "girlfriend",
    "gn": "good night",
    "gr8": "great",
    "gtg": "got to go",
    "hbd": "happy birthday",
    "hbu": "how about you",
    "idc": "I do not care",
    "idk": "I do not know",
    "ikr": "I know right",
    "imo": "in my opinion",
    "imho": "in my humble opinion",
    "irl": "in real life",
    "jk": "just kidding",
    "l8r": "later",
    "lmao": "laughing my head off",
    "lol": "laughing out loud",
    "luv": "love",
    "msg": "message",
    "nvm": "never mind",
    "np": "no problem",
    "nsfw": "not safe for work",
    "omg": "oh my God",
    "omw": "on my way",
    "otp": "one true pairing",
    "pls": "please",
    "plz": "please",
    "pov": "point of view",
    "r" : "are",
    "rofl": "rolling on the floor laughing",
    "rn": "right now",
    "smh": "shaking my head",
    "sob": "son of a gun",
    "soz": "sorry",
    "stfu": "shut the front door",
    "sup": "what is up",
    "tbh": "to be honest",
    "thx": "thanks",
    "tmi": "too much information",
    "ttyl": "talk to you later",
    "ty": "thank you",
    "u": "you",
    "ur": "your",
    "wanna": "want to",
    "wassup": "what is up",
    "wbu": "what about you",
    "wyd": "what are you doing",
    "wtf": "what the heck",
    "wth": "what the heck",
    "y" : "why",
    "ya": "you",
    "yolo": "you only live once",
    "yw": "you are welcome",
    "bruh": "brother",
    "lit": "exciting",
    "fam": "friends",
    "noob": "beginner",
    "prolly": "probably",
    "tho": "though",
    "aint": "is not",
    "lemme": "let me",
    "gimme": "give me",
    "bcuz": "because",
    "coz": "because",
    "cuz": "because"
}

In [184]:
def chat_conversion(text):
    new_text=[]
    for w in text.split():
        if w.lower() in chat_words:
            new_text.append(chat_words[w.lower()])
        else:
            new_text.append(w)
    return ' '.join(new_text)

text.split():

- Splits the sentence into words

- Default split is by whitespace

In [185]:
chat_conversion("Idk y u r late lol")

'I do not know why you are late laughing out loud'

#### 6. SPELLING CORRECTION

spelling mistakes can bring unecessary complexities in our model

In [186]:
from textblob import TextBlob

In [187]:
incorrect_text= 'ceartain conditns durriing several ggenerations aree nodified in the samme manner'
TextBlb= TextBlob(incorrect_text)
TextBlb.correct().string

'certain conditions during several generations are modified in the same manner'

TextBlob is good for:

- Quick prototyping

- Small projects

- Academic demos

But for production-level NLP:

- spaCy

- HuggingFace

- Transformers

#### 7. REMOVING STOP WORD 

Words like a, the, of, are, my etc are contributed to sentence formation but not in the meaning of the sentence

Removing common, less informative words from text before processing.

So, it won't be useful in sentiment analysis or any kind of things like that, so we need to remove it

In machine learning we need this to:

- Reduce vocabulary size
- Reduce noise
- Improve model efficiency
- Reduce dimentionality
- Improve TF-IDF performance

In [188]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [189]:
from nltk.corpus import stopwords

In [190]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [191]:
def remove_stopwords(text):
    new_text=[]

    for word in text.split():
        if word in stopwords.words('english'):
            new_text.append('')
        else:
            new_text.append(word)

    x = new_text[:]
    new_text.clear()
    return ' '.join(x)

In [192]:
remove_stopwords("NLTK tries to load the stopwords corpus file from your system.")

'NLTK tries  load  stopwords corpus file   system.'

#### 7. HANDLING EMOJIS

<U>*METHOD 1: USING <b>REGEX</b>*</U>

In [193]:
import re

def remove_emoji(text):
    emoji_pattern = re.compile(
        "["
        u"\U0001F600-\U0001F64F"  # emoticons
        u"\U0001F300-\U0001F5FF"  # symbols & pictographs
        u"\U0001F680-\U0001F6FF"  # transport & map
        u"\U0001F1E0-\U0001F1FF"  # flags
        u"\U00002700-\U000027BF"
        u"\U000024C2-\U0001F251"
        "]+",
        flags=re.UNICODE
    )
    return emoji_pattern.sub(r'',text)

In [194]:
text= "I love NLP 😍🔥🚀"
print(remove_emoji(text))

I love NLP

<U>*METHOD 2: USING <b>EMOJI</b> LIBRARY* </U>

In [195]:
import emoji

def remove_emoji1(text):
    return emoji.replace_emoji(text,replace='')

In [196]:
text= "I love NLP 😍🔥🚀"
print(remove_emoji1(text))

I love NLP

### <u><b>TOKENIZATION </b> </u>

Tokenization is the process of breaking text into smaller units called tokens.

since, machines can't undersatnd raw text, we need to convert it into numbers

Before converting text into vectors(Bag of words, TF-IDF, embeddings) we must first split text into meaningful units

eg:

I love NLP very much.

-> ["I", "love", "NLP", "very", "much"]

Types of TOKENIZATTION:

1. SENTENCE TOKENIZATION
2. WORD TOKENIZATION
3. CHARACTER TOKENIZATION
4. SUBWORD TOKENIZATION

<U>*METHOD 1: USING <b>SPLIT</b> FUNCTION*</U>

-> word tokenization

In [197]:
sent1 = 'I am going to delhi'
sent1.split()

['I', 'am', 'going', 'to', 'delhi']

-> sentence tokenization

In [198]:
sent2= 'I am going to delhi. I will stay there for 3 days. Let us hope the trip to be great.'
sent2.split('.')

['I am going to delhi',
 ' I will stay there for 3 days',
 ' Let us hope the trip to be great',
 '']

-> problem with split function

In [199]:
sent3= 'I am going to delhi!'
sent3.split()

['I', 'am', 'going', 'to', 'delhi!']

here the '!' is considered as a part of the word 'delhi'

In [200]:
sent4= 'where do you think I should go? I have 3 days holiday.'
sent4.split('.')

['where do you think I should go? I have 3 days holiday', '']

here, until the ? is not considered as a different sentence

<U>*METHOD 2: USING <b>NLTK</b> LIBRARY*</U>

NLTK (Natural Language Toolkit) is:

A Python library for teaching, learning, and experimenting with NLP.

It is mainly:

- Educational

- Research-oriented

- Good for understanding concepts

NLTK Provides:

- Tokenization

- Stopword removal

- Stemming

- Lemmatization

- POS tagging

- Chunking

- Basic sentiment analysis

- Corpora (WordNet, Gutenberg, etc.)

In [201]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [202]:
from nltk.tokenize import word_tokenize,sent_tokenize

In [203]:
sent1

'I am going to delhi'

In [204]:
word_tokenize(sent1,preserve_line=True)

['I', 'am', 'going', 'to', 'delhi']

In [207]:
import nltk
nltk.data.find('tokenizers/punkt')

FileSystemPathPointer('C:\\Users\\Admin\\AppData\\Roaming\\nltk_data\\tokenizers\\punkt')

In [208]:
text= """
Dr. John Smith lives in the U.S.A. He works at Google Inc. as a senior AI researcher.
Every morning, he wakes up at 6:30 a.m., drinks coffee, and reads the news.
"Artificial Intelligence is the future!" he often says.
Last week, he visited New York. It was amazing, wasn't it?
He met Prof. Williams there, and they discussed NLP, ML, and robotics.
Can machines really think like humans? That is the big question.
"""

<U>*METHOD 3: USING <b>spaCy</b> LIBRARY*</U>

spaCy is:

An industrial-strength NLP library designed for production use.

It is:
- Fast
- Modern
- Built in Cython
- Used in real world systems

spaCy provides:

- Tokenization
- POS tagging
- Named Entity Recognition(NER)
- Dependency Parsing
- Lemmetization
- Word vectors
- Pipeline architecture
- Transformer integration

In [211]:
import spacy
nlp= spacy.load('en_core_web_sm')

The variable name is used as nlp , becuause to represent the processing pipeline

In [217]:
doc1=nlp(sent1)
doc2=nlp('I have a ph.D')
doc3=nlp(sent3)
print(doc1)
print(sent1)

I am going to delhi
I am going to delhi

Even if it's just one sentence, spaCy treats everything as a document. that's why every sentence is converted to document

In NLP, everything is a document — even a single word.

In [218]:
for token in doc2:
    print(token)

I
have
a
ph
.
D

In [219]:
# SENTENCE TOKENIZATION USING SPACY

import spacy

nlp= spacy.load('en_core_web_sm')

text= 'I love NLP. It is amazing! spacy is powerful, isn,t it?'

doc=nlp(text)

for sent in doc.sents:
    print(sent.text)

I love NLP.
It is amazing!
spacy is powerful, isn,t it?

### <u><b>STEMMING</b> </u>

The process of reducing a word to its root (base) form by cutting off suffixes.

it removes endings like:
- -ing
- -ed
- -ly
- un- 
- -s etc

In [220]:
from nltk.stem.porter import PorterStemmer

ps=PorterStemmer()
def stem_words(text):
    return ' '.join([ps.stem(word) for word in text.split()])

In [221]:
sample= ' walk walks walking walked'
stem_words(sample)

'walk walk walk walk'

In [222]:
text= """
Dr. John Smith lives in the U.S.A. He works at Google Inc. as a senior AI researcher.
Every morning, he wakes up at 6:30 a.m., drinks coffee, and reads the news.
"Artificial Intelligence is the future!" he often says.
Last week, he visited New York. It was amazing, wasn't it?
He met Prof. Williams there, and they discussed NLP, ML, and robotics.
Can machines really think like humans? That is the big question.
"""

stem_words(text)

'dr. john smith live in the u.s.a. he work at googl inc. as a senior ai researcher. everi morning, he wake up at 6:30 a.m., drink coffee, and read the news. "artifici intellig is the future!" he often says. last week, he visit new york. it wa amazing, wasn\'t it? he met prof. william there, and they discuss nlp, ml, and robotics. can machin realli think like humans? that is the big question.'

We can find that every word is tried to be converted to it's root form

but we can fimd a number of mistakes here in this , since every word can't be recognised as an actaul english word

that's why lemmetization is used

### <u><b>LEMMATIZATION</b> </u>

Lemmetization, unike Stemming , reduces the inflected words properly ensuring that the root word belongs to the language . In lemmetization root word is called Lemma. A lemma is the canonical form, dictionary form, criterion form os a set of words

In [ ]:
import nltk
nltk.download('wordnet')
nltk.download('omw-1.4')

from nltk.stem import WordNetLemmatizer
wordnet_lemmatizer= WordNetLemmatizer()

sentence= 'I love NLP. It is amazing! spacy is powerful, isn,t it?'
punctuations= "?:!.,;"
sentence_words=nltk.word_tokenize(sentence,preserve_line=True) #This splits the sentence into tokens (words and punctuation).
for word in sentence_words:
    if word in punctuations:
        sentence_words.remove(word)
#sentence_words
print('{0:20}{1:20}'.format('Word','Lemma'))
for word in sentence_words:
    print('{0:20}{1:20}'.format(word,wordnet_lemmatizer.lemmatize(word)))

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...

Word                Lemma
I                   I
love                love
NLP.                NLP.
It                  It
is                  is
amazing             amazing
spacy               spacy
is                  is
powerful            powerful
isn                 isn
t                   t
it                  it